name = "pbl-gairon-test"
main = "src/index.ts"
compatibility_date = "2023-10-30"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "pbl-db"
database_id = "af8fdeea-d678-4c4d-bef8-4d3612fd550f"

[[kv_namespaces]]
binding = "KV"
id = "0353bc1ada254815a5c8f697e87d7284"

[triggers]
crons = ["*/1 * * * *"]