name = "pbl-gairon-test"
main = "src/index.ts"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "pbl-db"
database_id = "ae09415c-25c0-4780-b64b-a69546f3f8ea"

[[kv_namespaces]]
binding = "KV"
id = "0353bc1ada254815a5c8f697e87d7284"